version: "3.9"

services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  test:
    build: .
    container_name: fastapi-tests
    depends_on:
      - mongodb
    working_dir: /app
    env_file:
      - .env.test
    environment:
      PYTHONPATH: /app
    entrypoint: [ "pytest" ]
    command: [ "tests/", "--disable-warnings" ]

  cli:
    build: .
    container_name: fastapi-cli
    env_file:
      - .env
    depends_on:
      - mongodb
    entrypoint: ["python", "cli/cli.py"]